// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

/// @title DonationVault
/// @notice Escrow contract for milestone-based NGO donations on Rootstock
/// @dev Funds are released by a verifier upon milestone completion.
///      Donors can reclaim after 90 days of inactivity.
///      A per-donor cap prevents any single address dominating the pool.
///      Verifier rotation uses a 2-day time-locked handoff; the NGO holds
///      an emergency override once the vault has expired.
contract DonationVault {

    // ─── State ────────────────────────────────────────────────────────────

    /// @notice Address of the NGO receiving released milestone funds
    /// @dev Public so the frontend and donors can verify the beneficiary
    ///      without needing a separate getter function.
    address public ngo;

    /// @notice Address authorized to release milestones
    /// @dev Public so donors can independently verify who controls
    ///      milestone releases without trusting the frontend.
    address public verifier;

    /// @notice Proposed successor verifier (zero if no handoff in progress)
    /// @dev Set by requestVerifierHandoff; cleared after acceptVerifierHandoff.
    address public pendingVerifier;

    /// @notice Block timestamp when the current handoff request was made
    /// @dev Used to enforce HANDOFF_DELAY before the successor can accept.
    uint256 public verifierHandoffRequestedAt;

    /// @notice Human-readable campaign description
    /// @dev Public so any frontend can render campaign details without
    ///      relying on off-chain storage or a subgraph.
    string public description;

    /// @notice Total fundraising target in wei
    /// @dev Public to allow progress-bar calculation: totalRaised / targetAmount.
    uint256 public targetAmount;

    /// @notice Total amount accepted (after cap/overflow) so far in wei
    /// @dev Public so the frontend can display live funding progress.
    uint256 public totalRaised;

    /// @notice Timestamp of last contract activity (donation or milestone release)
    /// @dev Public so donors can independently calculate days remaining
    ///      before the refund window opens (lastUpdateTimestamp + EXPIRY_WINDOW).
    uint256 public lastUpdateTimestamp;

    /// @notice Maximum a single address may contribute in total
    /// @dev Set to 10 % of targetAmount in the constructor.
    ///      Prevents any one donor from dominating the pool or spamming.
    uint256 public maxContributionPerDonor;

    /// @notice Inactivity period after which donors may claim refunds
    uint256 public constant EXPIRY_WINDOW = 90 days;

    /// @notice Minimum delay between a handoff request and acceptance
    /// @dev Gives the community time to detect and react to a rogue handoff.
    uint256 public constant HANDOFF_DELAY = 2 days;

    /// @notice Represents a single fundraising milestone
    struct Milestone {
        uint256 amount;     // wei to release upon completion
        bool released;      // whether funds have been sent to NGO
        string description; // human-readable milestone description
    }

    /// @notice Ordered array of milestones for this campaign
    /// @dev Public getter generated by Solidity; use milestoneCount() for length.
    Milestone[] public milestones;

    /// @notice Tracks each donor's total accepted contribution in wei
    /// @dev Public so donors can verify their own balance on-chain.
    ///      Zeroed before transfer in claimRefund (checks-effects-interactions).
    mapping(address => uint256) public contributions;

    // ─── Custom Errors ────────────────────────────────────────────────────

    /// @dev _ngo or _verifier supplied as address(0)
    error ZeroAddress();

    /// @dev _milestoneAmounts and _milestoneDescriptions have different lengths
    error MilestoneMismatch();

    /// @dev Sum of milestone amounts does not equal targetAmount
    error MilestoneSumMismatch();

    /// @dev Donation attempted after totalRaised has reached targetAmount
    error TargetReached();

    /// @dev Zero-value donation attempted
    error ZeroDonation();

    /// @dev Caller is not the verifier
    error OnlyVerifier();

    /// @dev Caller is not the NGO
    error OnlyNgo();

    /// @dev _index is out of bounds for the milestones array
    error InvalidMilestone();

    /// @dev Milestone has already been released
    error AlreadyReleased();

    /// @dev Contract balance is below the milestone amount (should not occur normally)
    error InsufficientFunds();

    /// @dev claimRefund called before EXPIRY_WINDOW has elapsed
    error NotExpired();

    /// @dev claimRefund called by an address with zero contribution
    error NoContribution();

    /// @dev Donation would push this donor's total past maxContributionPerDonor
    error ExceedsDonorCap();

    /// @dev acceptVerifierHandoff called when no handoff is pending
    error NoPendingHandoff();

    /// @dev acceptVerifierHandoff called before HANDOFF_DELAY has elapsed
    error HandoffTooEarly();

    // ─── Events ───────────────────────────────────────────────────────────

    /// @notice Emitted when a donation is accepted
    /// @param donor   Address that donated
    /// @param amount  Wei amount accepted (may be less than msg.value if capped)
    event Donated(address indexed donor, uint256 amount);

    /// @notice Emitted when the verifier releases a milestone
    /// @param index  Zero-based milestone index
    /// @param amount Wei transferred to the NGO
    event MilestoneReleased(uint256 indexed index, uint256 indexed amount);

    /// @notice Emitted when a donor successfully claims a refund
    /// @param donor   Address that claimed
    /// @param amount  Wei returned
    event RefundClaimed(address indexed donor, uint256 indexed amount);

    /// @notice Emitted when the verifier role changes
    /// @param oldVerifier Previous verifier address
    /// @param newVerifier New verifier address
    event VerifierUpdated(address indexed oldVerifier, address indexed newVerifier);

    /// @notice Emitted when a verifier handoff is requested (starts the 2-day clock)
    /// @param currentVerifier Address that initiated the request
    /// @param proposed        Address that will become verifier after the delay
    /// @param unlockAt        Timestamp after which the proposed address may accept
    event VerifierHandoffRequested(
        address indexed currentVerifier,
        address indexed proposed,
        uint256 unlockAt
    );

    // ─── Constructor ──────────────────────────────────────────────────────

    /// @notice Deploy a new DonationVault
    /// @param _ngo                   Address that receives released milestone funds (non-zero)
    /// @param _verifier              Address authorized to release milestones (non-zero)
    /// @param _description           Campaign description string
    /// @param _targetAmount          Total fundraising target in wei
    /// @param _milestoneAmounts      Per-milestone release amounts — must sum to _targetAmount
    /// @param _milestoneDescriptions Descriptions matching _milestoneAmounts in length
    constructor(
        address _ngo,
        address _verifier,
        string memory _description,
        uint256 _targetAmount,
        uint256[] memory _milestoneAmounts,
        string[] memory _milestoneDescriptions
    ) {
        if (_ngo == address(0)) revert ZeroAddress();
        if (_verifier == address(0)) revert ZeroAddress();
        if (_milestoneAmounts.length != _milestoneDescriptions.length) revert MilestoneMismatch();

        // Validate that milestone amounts sum exactly to the target
        uint256 sum = 0;
        for (uint256 i = 0; i < _milestoneAmounts.length; i++) {
            sum += _milestoneAmounts[i];
        }
        if (sum != _targetAmount) revert MilestoneSumMismatch();

        ngo               = _ngo;
        verifier          = _verifier;
        description       = _description;
        targetAmount      = _targetAmount;
        lastUpdateTimestamp = block.timestamp;

        // 10 % of target — prevents any single donor dominating the pool.
        // Integer division floors toward zero, which is acceptable.
        maxContributionPerDonor = _targetAmount / 10;

        for (uint256 i = 0; i < _milestoneAmounts.length; i++) {
            milestones.push(Milestone(_milestoneAmounts[i], false, _milestoneDescriptions[i]));
        }
    }

    // ─── Donation ─────────────────────────────────────────────────────────

    /// @notice Donate to the campaign
    /// @dev Any amount that would push totalRaised past targetAmount is automatically
    ///      refunded. A single donor may not exceed maxContributionPerDonor in total.
    ///      Zero-value calls revert with ZeroDonation.
    function donate() public payable {
        if (msg.value == 0) revert ZeroDonation();
        if (totalRaised >= targetAmount) revert TargetReached();

        // Cap accepted amount so totalRaised never exceeds targetAmount
        uint256 accepted = msg.value;
        if (totalRaised + msg.value > targetAmount) {
            accepted = targetAmount - totalRaised;
            payable(msg.sender).transfer(msg.value - accepted);
        }

        // Enforce per-donor cap
        if (contributions[msg.sender] + accepted > maxContributionPerDonor) {
            revert ExceedsDonorCap();
        }

        contributions[msg.sender] += accepted;
        totalRaised               += accepted;
        lastUpdateTimestamp        = block.timestamp;

        emit Donated(msg.sender, accepted);
    }

    // ─── Milestone Release ────────────────────────────────────────────────

    /// @notice Release a milestone's funds to the NGO
    /// @dev Only callable by the verifier. Follows checks-effects-interactions.
    /// @param _index Zero-based index of the milestone to release
    function releaseMilestone(uint256 _index) external {
        if (msg.sender != verifier)            revert OnlyVerifier();
        if (_index >= milestones.length)       revert InvalidMilestone();
        if (milestones[_index].released)       revert AlreadyReleased();
        if (address(this).balance < milestones[_index].amount) revert InsufficientFunds();

        milestones[_index].released = true;
        lastUpdateTimestamp         = block.timestamp;
        payable(ngo).transfer(milestones[_index].amount);

        emit MilestoneReleased(_index, milestones[_index].amount);
    }

    // ─── Refund ───────────────────────────────────────────────────────────

    /// @notice Claim a full refund of your contribution
    /// @dev Only available after EXPIRY_WINDOW of contract inactivity.
    ///      Zeroes the balance before transfer (reentrancy-safe).
    function claimRefund() external {
        if (block.timestamp <= lastUpdateTimestamp + EXPIRY_WINDOW) revert NotExpired();

        uint256 amount = contributions[msg.sender];
        if (amount == 0) revert NoContribution();

        contributions[msg.sender] = 0;
        payable(msg.sender).transfer(amount);

        emit RefundClaimed(msg.sender, amount);
    }

    // ─── Verifier Rotation ────────────────────────────────────────────────

    /// @notice Step 1: current verifier proposes a successor
    /// @dev Starts a 2-day clock. The proposed address must then call
    ///      acceptVerifierHandoff after HANDOFF_DELAY has elapsed.
    ///      Overwrites any pending handoff already in progress.
    /// @param _proposed Address of the proposed new verifier (non-zero)
    function requestVerifierHandoff(address _proposed) external {
        if (msg.sender != verifier)  revert OnlyVerifier();
        if (_proposed == address(0)) revert ZeroAddress();

        pendingVerifier              = _proposed;
        verifierHandoffRequestedAt   = block.timestamp;

        emit VerifierHandoffRequested(verifier, _proposed, block.timestamp + HANDOFF_DELAY);
    }

    /// @notice Step 2: proposed verifier accepts after the delay has elapsed
    /// @dev The 2-day delay gives donors time to react before the change takes effect.
    function acceptVerifierHandoff() external {
        if (pendingVerifier == address(0))                              revert NoPendingHandoff();
        if (msg.sender != pendingVerifier)                              revert OnlyVerifier();
        if (block.timestamp < verifierHandoffRequestedAt + HANDOFF_DELAY) revert HandoffTooEarly();

        emit VerifierUpdated(verifier, pendingVerifier);
        verifier                   = pendingVerifier;
        pendingVerifier            = address(0);
        verifierHandoffRequestedAt = 0;
    }

    /// @notice Emergency path: NGO forcibly replaces a lost or compromised verifier
    /// @dev Only callable by the NGO, and only after EXPIRY_WINDOW of inactivity.
    ///      At that point donors are already entitled to full refunds, so there is
    ///      no incremental risk from the NGO controlling both roles.
    /// @param _newVerifier Replacement verifier address (non-zero)
    function emergencyReplaceVerifier(address _newVerifier) external {
        if (msg.sender != ngo)        revert OnlyNgo();
        if (_newVerifier == address(0)) revert ZeroAddress();
        if (block.timestamp <= lastUpdateTimestamp + EXPIRY_WINDOW) revert NotExpired();

        emit VerifierUpdated(verifier, _newVerifier);
        verifier = _newVerifier;
    }

    // ─── Views ────────────────────────────────────────────────────────────

    /// @notice Returns the total number of milestones
    /// @dev Exposed so the frontend does not need to brute-force indices.
    /// @return count Number of milestones in this vault
    function milestoneCount() external view returns (uint256) {
        return milestones.length;
    }

    // ─── Fallback ─────────────────────────────────────────────────────────

    /// @dev Accept plain ETH transfers as donations
    receive() external payable {
        donate();
    }
}
